# Generated by Django 4.0.3 on 2022-03-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='first_name',
            field=models.CharField(default='jhon', max_length=250),
        ),
        migrations.AddField(
            model_name='salary',
            name='last_name',
            field=models.CharField(default='elton', max_length=250),
        ),
    ]
